### ISSUE TITLE
Review issues

### ISSUE THREAD

**Issue by robinwhittleton** [drgrigg/m-e-braddon_the-cloven-foot#1]
Right, only a few things:

content.opf:
- longdesc: cirumvent -> circumvent
- longdesc: simplifing -> simplifying

chapter-15:
- all signed “Chicot.”

chapter-16:
- she told herself’ <- errant apostrophe
- “At half-past seven.”, <- errant comma

chapter-33:
- full of distractions’. <- guess this should end .”

chapter-35:
- C’est tres bien dit. <- tres should be très
- Couple of references to “cure” in this chapter that should be “curé” like the rest of the book

**Comment by drgrigg** [comment]
Robin, 

I don't understand why you've flagged the issue in chapter 15? I can't see anything wrong with the way I have it.

All the others should now be fixed.

**Comment by robinwhittleton** [comment]
Oops, I got half way through writing an issue that they should have signature semantics, then changed my mind but forgot to delete it 🤦‍♂️

**Comment by robinwhittleton** [comment]
Did you push your fixes? I’m not seeing them.

**Comment by drgrigg** [comment]
Whoops! Sorry. Done now.

Regards,

David
